micronaut:
  application:
    name: gabriel
datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/pix`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}



jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true

client:
  http:
    itau: ${ITAU_URL:`http://localhost:9091/api/v1/clientes`}
    bcb: ${BCB_URL:`http://localhost:8082/api/v1/pix/keys`}



